# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # tells CocoaPods to use dynamic frameworks instead of static libraries
  use_frameworks!

  # install all Flutter dependencies, like firebase_core and cloud_firestore as iOS pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # this will run the tests in the RunnerTests directory
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# Version 0 - from Cursor
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#   end
# end

# Version 1 - from Google
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     if target.name == 'BoringSSL-GRPC'
#       target.source_build_phase.files.each do |file|
#         if file.settings && file.settings['COMPILER_FLAGS']
#           flags = file.settings['COMPILER_FLAGS'].split
#           flags.reject! { |flag| flag == '-Wno-error=deprecated-declarations' }
#           file.settings['COMPILER_FLAGS'] = flags.join(' ')
#         end
#       end
#     end
#     flutter_additional_ios_build_settings(target)
#     target.build_configurations.each do |config|
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#     end
#   end
# end

# Version 2 - from Cursor AI
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#     target.build_configurations.each do |config|
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
#       # Fix for Firebase iOS build issues
#       config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
#         '$(inherited)',
#         'PERMISSION_CAMERA=1',
#         'PERMISSION_PHOTOS=1',
#         'PERMISSION_LOCATION=1',
#       ]
#     end
#   end
# end

# Version 3 - from Cursor AI
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
