// Mocks generated by Mockito 5.4.6 from annotations
// in spanish_vocab/test/screens/word_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spanish_vocab/models/vocab_word.dart' as _i4;
import 'package:spanish_vocab/services/firebase_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i2.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addDocument(_i4.VocabWord? word) => (super.noSuchMethod(
        Invocation.method(
          #addDocument,
          [word],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateVocabWord(_i4.VocabWord? word) => (super.noSuchMethod(
        Invocation.method(
          #updateVocabWord,
          [word],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.VocabWord>> getVocabWords() => (super.noSuchMethod(
        Invocation.method(
          #getVocabWords,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.VocabWord>>.empty(),
      ) as _i3.Stream<List<_i4.VocabWord>>);

  @override
  _i3.Future<void> deleteVocabWord(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteVocabWord,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
